name: npm_publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install pnpm
        run: npm i -g pnpm@latest
      - name: Install dependencies and build
        run: pnpm install --no-frozen-lockfile && pnpm -r build
      - name: check and publish
        run: if sh .ci/check-packages-can-publish.sh; then pnpm publish packages/vue-preview-imgs --no-git-checks; fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
